# Generated by Django 2.2.3 on 2019-07-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('book_publication', models.CharField(max_length=30)),
                ('book_qty', models.IntegerField()),
                ('book_price', models.FloatField()),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
    ]
